export const rates = {
  status: 200,
  data: {
    rates: [
      {
        additional_services_surcharge: 0,
        available_handover_options: [
          "dropoff"
        ],
        cost_rank: 1,
        courier_id: "97f58ec6-57d5-47b6-828d-caa4f762a935",
        courier_logo_url: "https://storage.googleapis.com/easyship-assets/website/courier-logos/color-img/fedex.png",
        courier_name: "FedEx® International Connect Plus",
        courier_remarks: "Remote Area Surcharge may apply",
        currency: "USD",
        ddp_handling_fee: 0,
        delivery_time_rank: 1,
        description: "Estimated  8.54 tax & duty due on delivery (Tax handling fees may apply)",
        discount: {
          amount: 0,
          origin_amount: 0
        },
        easyship_rating: null,
        estimated_import_duty: 4,
        estimated_import_tax: 4.54,
        fuel_surcharge: 12.18,
        full_description: "FedEx® International Connect Plus (2-5 working days) Estimated  8.54 tax & duty due on delivery (Tax handling fees may apply)",
        import_duty_charge: 0,
        import_tax_charge: 0,
        import_tax_non_chargeable: 0,
        incoterms: "DDU",
        insurance_fee: 0,
        is_above_threshold: true,
        max_delivery_time: 5,
        min_delivery_time: 2,
        minimum_pickup_fee: 0,
        other_surcharges: null,
        oversized_surcharge: 0,
        payment_recipient: "Easyship",
        provincial_sales_tax: 0,
        rates_in_origin_currency: {
          additional_services_surcharge: 0,
          currency: "USD",
          ddp_handling_fee: 0,
          estimated_import_duty: 4,
          estimated_import_tax: 4.54,
          fuel_surcharge: 12.18,
          import_duty_charge: 0,
          import_tax_charge: 0,
          import_tax_non_chargeable: 0,
          insurance_fee: 0,
          minimum_pickup_fee: 0,
          oversized_surcharge: 0,
          provincial_sales_tax: 0,
          remote_area_surcharge: 0,
          residential_discounted_fee: 0,
          residential_full_fee: 0,
          sales_tax: 0,
          shipment_charge: 58.68,
          shipment_charge_total: 70.86,
          total_charge: 70.86,
          warehouse_handling_fee: 0
        },
        remote_area_surcharge: 0,
        remote_area_surcharges: null,
        residential_discounted_fee: 0,
        residential_full_fee: 0,
        sales_tax: 0,
        shipment_charge: 58.68,
        shipment_charge_total: 70.86,
        total_charge: 70.86,
        tracking_rating: 3,
        value_for_money_rank: 1,
        warehouse_handling_fee: 0
      },
      {
        additional_services_surcharge: 0,
        available_handover_options: [
          "dropoff",
          "free_pickup"
        ],
        cost_rank: 2,
        courier_id: "7ba591f0-f140-4831-b702-70a1cc1462b9",
        courier_logo_url: "https://storage.googleapis.com/easyship-assets/website/courier-logos/color-img/passport.png",
        courier_name: "Passport - Priority Delcon",
        courier_remarks: null,
        currency: "USD",
        ddp_handling_fee: 0,
        delivery_time_rank: 5,
        description: "Estimated  9.17 tax & duty due on delivery (Tax handling fees may apply)",
        discount: {
          amount: 0,
          origin_amount: 0
        },
        easyship_rating: null,
        estimated_import_duty: 4,
        estimated_import_tax: 5.17,
        fuel_surcharge: 0,
        full_description: "Passport - Priority Delcon (7-12 working days) Estimated  9.17 tax & duty due on delivery (Tax handling fees may apply)",
        import_duty_charge: 0,
        import_tax_charge: 0,
        import_tax_non_chargeable: 0,
        incoterms: "DDU",
        insurance_fee: 0,
        is_above_threshold: true,
        max_delivery_time: 12,
        min_delivery_time: 7,
        minimum_pickup_fee: 0,
        other_surcharges: null,
        oversized_surcharge: 0,
        payment_recipient: "Easyship",
        provincial_sales_tax: 0,
        rates_in_origin_currency: {
          additional_services_surcharge: 0,
          currency: "USD",
          ddp_handling_fee: 0,
          estimated_import_duty: 4,
          estimated_import_tax: 5.17,
          fuel_surcharge: 0,
          import_duty_charge: 0,
          import_tax_charge: 0,
          import_tax_non_chargeable: 0,
          insurance_fee: 0,
          minimum_pickup_fee: 0,
          oversized_surcharge: 0,
          provincial_sales_tax: 0,
          remote_area_surcharge: 0,
          residential_discounted_fee: null,
          residential_full_fee: null,
          sales_tax: 0,
          shipment_charge: 83.33,
          shipment_charge_total: 83.33,
          total_charge: 83.33,
          warehouse_handling_fee: 0
        },
        remote_area_surcharge: 0,
        remote_area_surcharges: null,
        residential_discounted_fee: null,
        residential_full_fee: null,
        sales_tax: 0,
        shipment_charge: 83.33,
        shipment_charge_total: 83.33,
        total_charge: 83.33,
        tracking_rating: 2,
        value_for_money_rank: 2,
        warehouse_handling_fee: 0
      },
      {
        additional_services_surcharge: 0,
        available_handover_options: [
          "dropoff",
          "free_pickup"
        ],
        cost_rank: 3,
        courier_id: "7f81ad1e-c84f-452a-a04c-15585e0ca7a3",
        courier_logo_url: "https://storage.googleapis.com/easyship-assets/website/courier-logos/color-img/usps.png",
        courier_name: "USPS - Priority Mail International",
        courier_remarks: null,
        currency: "USD",
        ddp_handling_fee: 0,
        delivery_time_rank: 4,
        description: "Estimated  12.2 tax & duty due on delivery (Tax handling fees may apply)",
        discount: {
          amount: 0,
          origin_amount: 0
        },
        easyship_rating: null,
        estimated_import_duty: 4,
        estimated_import_tax: 8.2,
        fuel_surcharge: 0,
        full_description: "USPS - Priority Mail International (8-10 working days) Estimated  12.2 tax & duty due on delivery (Tax handling fees may apply)",
        import_duty_charge: 0,
        import_tax_charge: 0,
        import_tax_non_chargeable: 0,
        incoterms: "DDU",
        insurance_fee: 0,
        is_above_threshold: true,
        max_delivery_time: 10,
        min_delivery_time: 8,
        minimum_pickup_fee: 0,
        other_surcharges: null,
        oversized_surcharge: 18,
        payment_recipient: "Easyship",
        provincial_sales_tax: 0,
        rates_in_origin_currency: {
          additional_services_surcharge: 0,
          currency: "USD",
          ddp_handling_fee: 0,
          estimated_import_duty: 4,
          estimated_import_tax: 8.2,
          fuel_surcharge: 0,
          import_duty_charge: 0,
          import_tax_charge: 0,
          import_tax_non_chargeable: 0,
          insurance_fee: 0,
          minimum_pickup_fee: 0,
          oversized_surcharge: 18,
          provincial_sales_tax: 0,
          remote_area_surcharge: 0,
          residential_discounted_fee: null,
          residential_full_fee: null,
          sales_tax: 0,
          shipment_charge: 126.02,
          shipment_charge_total: 144.02,
          total_charge: 144.02,
          warehouse_handling_fee: 0
        },
        remote_area_surcharge: 0,
        remote_area_surcharges: null,
        residential_discounted_fee: null,
        residential_full_fee: null,
        sales_tax: 0,
        shipment_charge: 126.02,
        shipment_charge_total: 144.02,
        total_charge: 144.02,
        tracking_rating: 2,
        value_for_money_rank: 3,
        warehouse_handling_fee: 0
      },
      {
        additional_services_surcharge: 0,
        available_handover_options: [
          "dropoff"
        ],
        cost_rank: 5,
        courier_id: "3f594a89-3658-4e36-b748-dc31711b2499",
        courier_logo_url: "https://storage.googleapis.com/easyship-assets/website/courier-logos/color-img/fedex.png",
        courier_name: "FedEx International Priority®",
        courier_remarks: "Remote Area Surcharge may apply",
        currency: "USD",
        ddp_handling_fee: 0,
        delivery_time_rank: 2,
        description: "Estimated  24.64 tax & duty due on delivery (Tax handling fees may apply)",
        discount: {
          amount: 0,
          origin_amount: 0
        },
        easyship_rating: null,
        estimated_import_duty: 4,
        estimated_import_tax: 20.64,
        fuel_surcharge: 67.49,
        full_description: "FedEx International Priority® (3-5 working days) Estimated  24.64 tax & duty due on delivery (Tax handling fees may apply)",
        import_duty_charge: 0,
        import_tax_charge: 0,
        import_tax_non_chargeable: 0,
        incoterms: "DDU",
        insurance_fee: 0,
        is_above_threshold: true,
        max_delivery_time: 5,
        min_delivery_time: 3,
        minimum_pickup_fee: 0,
        other_surcharges: null,
        oversized_surcharge: 0,
        payment_recipient: "Easyship",
        provincial_sales_tax: 0,
        rates_in_origin_currency: {
          additional_services_surcharge: 0,
          currency: "USD",
          ddp_handling_fee: 0,
          estimated_import_duty: 4,
          estimated_import_tax: 20.64,
          fuel_surcharge: 67.49,
          import_duty_charge: 0,
          import_tax_charge: 0,
          import_tax_non_chargeable: 0,
          insurance_fee: 0,
          minimum_pickup_fee: 0,
          oversized_surcharge: 0,
          provincial_sales_tax: 0,
          remote_area_surcharge: 0,
          residential_discounted_fee: 0,
          residential_full_fee: 0,
          sales_tax: 0,
          shipment_charge: 325.25,
          shipment_charge_total: 392.74,
          total_charge: 392.74,
          warehouse_handling_fee: 0
        },
        remote_area_surcharge: 0,
        remote_area_surcharges: null,
        residential_discounted_fee: 0,
        residential_full_fee: 0,
        sales_tax: 0,
        shipment_charge: 325.25,
        shipment_charge_total: 392.74,
        total_charge: 392.74,
        tracking_rating: 3,
        value_for_money_rank: 4,
        warehouse_handling_fee: 0
      },
      {
        additional_services_surcharge: 0,
        available_handover_options: [
          "dropoff"
        ],
        cost_rank: 4,
        courier_id: "c00fbdf1-ad8b-42ff-a5dc-15e56ba79c84",
        courier_logo_url: "https://storage.googleapis.com/easyship-assets/website/courier-logos/color-img/fedex.png",
        courier_name: "FedEx International Economy®",
        courier_remarks: "Remote Area Surcharge may apply",
        currency: "USD",
        ddp_handling_fee: 0,
        delivery_time_rank: 3,
        description: "Estimated  23.88 tax & duty due on delivery (Tax handling fees may apply)",
        discount: {
          amount: 0,
          origin_amount: 0
        },
        easyship_rating: null,
        estimated_import_duty: 4,
        estimated_import_tax: 19.88,
        fuel_surcharge: 64.89,
        full_description: "FedEx International Economy® (5-6 working days) Estimated  23.88 tax & duty due on delivery (Tax handling fees may apply)",
        import_duty_charge: 0,
        import_tax_charge: 0,
        import_tax_non_chargeable: 0,
        incoterms: "DDU",
        insurance_fee: 0,
        is_above_threshold: true,
        max_delivery_time: 6,
        min_delivery_time: 5,
        minimum_pickup_fee: 0,
        other_surcharges: null,
        oversized_surcharge: 0,
        payment_recipient: "Easyship",
        provincial_sales_tax: 0,
        rates_in_origin_currency: {
          additional_services_surcharge: 0,
          currency: "USD",
          ddp_handling_fee: 0,
          estimated_import_duty: 4,
          estimated_import_tax: 19.88,
          fuel_surcharge: 64.89,
          import_duty_charge: 0,
          import_tax_charge: 0,
          import_tax_non_chargeable: 0,
          insurance_fee: 0,
          minimum_pickup_fee: 0,
          oversized_surcharge: 0,
          provincial_sales_tax: 0,
          remote_area_surcharge: 0,
          residential_discounted_fee: 0,
          residential_full_fee: 0,
          sales_tax: 0,
          shipment_charge: 312.7,
          shipment_charge_total: 377.59,
          total_charge: 377.59,
          warehouse_handling_fee: 0
        },
        remote_area_surcharge: 0,
        remote_area_surcharges: null,
        residential_discounted_fee: 0,
        residential_full_fee: 0,
        sales_tax: 0,
        shipment_charge: 312.7,
        shipment_charge_total: 377.59,
        total_charge: 377.59,
        tracking_rating: 3,
        value_for_money_rank: 5,
        warehouse_handling_fee: 0
      }
    ],
    meta: {
      pagination: {
        page: 1,
        next: null,
        count: 5
      },
      request_id: "bffe0fac0635bc3881614ad966173d77"
    }
  }
}